### ISSUE TITLE
opis problema

### ISSUE THREAD

**Issue by tomazc** [JernejHabjan/PR17_MV_JH#1]
"Predlagam, da izbereta prvi problem (airbnb). Je vsekako bolj zanimiv. Zanimiv je tudi predlog kombiniranja registracij in tehničnih pregledov.
Kodo in poročilo (v .md) dodajajte sproti. "

**Comment by JernejHabjan** [comment]
Avaliable on:
https://dataminingmaticjernej.azurewebsites.net/

Example -> New York - Asheville
